# Generated by Django 4.2 on 2023-05-01 13:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('subscriber_url', models.TextField(blank=True, null=True)),
                ('domain', models.CharField(choices=[('mobility', 'Mobility'), ('logistics', 'Logistics'), ('retail', 'Retail')], db_index=True, max_length=10)),
                ('type', models.CharField(blank=True, choices=[('BAP', 'Bap'), ('BPP', 'Bpp'), ('BG', 'Bg')], db_index=True, max_length=10, null=True)),
                ('msn', models.BooleanField(default=False)),
                ('city_code', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), db_index=True, size=None)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('subscriber_id', models.CharField(db_index=True, editable=False, max_length=265)),
                ('callback_url', models.TextField(unique=True)),
                ('country', models.CharField(max_length=3)),
                ('key_pair', models.JSONField(default=dict)),
                ('gst', models.JSONField(default=dict)),
                ('pan', models.JSONField(default=dict)),
                ('name_of_authorised_signatory', models.CharField(max_length=80)),
                ('address_of_authorised_signatory', models.TextField()),
                ('email_id', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=10)),
                ('type', models.CharField(blank=True, choices=[('BAP', 'Bap'), ('BPP', 'Bpp'), ('BG', 'Bg')], db_index=True, max_length=10, null=True)),
                ('unique_key_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('UNDER_SUBSCRIPTION', 'Under Subscription'), ('SUBSCRIBED', 'Subscribed'), ('INVALID_SSL', 'Invalid Ssl'), ('UNSUBSCRIBED', 'Unsubscribed')], default='INITIATED', max_length=20)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerOnRecord',
            fields=[
                ('unique_key_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('key_pair', models.JSONField(default=dict)),
                ('city_code', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), db_index=True, size=None)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('network_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_on_record', to='registry.networkparticipant')),
            ],
        ),
        migrations.AddField(
            model_name='networkparticipant',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_participant', to='registry.subscriber'),
        ),
    ]
