# Generated by Django 4.2 on 2023-05-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='callback_url',
            field=models.TextField(),
        ),
    ]
